[build]
builder = "nixpacks"
buildCommand = "cd ui && yarn install && yarn build && cd .. && yarn install && yarn tsc --project tsconfig.json"

[nixpacks]
nodejs_version = "20"

[deploy.env]
DATABASE_URL = "${DATABASE_URL}"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"

[[services]]
name = "web"
type = "web"
env = "production"
autoDeploy = true
healthCheck = "/"

[mounts]
source = "data"
destination = "/data"
